### PR TITLE
Fix cassandra-topology.properties removal

### LINKED ISSUE #477: Fix `cassandra-topology.properties` removal
Commit https://github.com/k8ssandra/management-api-for-apache-cassandra/commit/1c79885cec838bfedc73b802f7b63ec6f3c7de0c attempted to remove the topology file from the images by doing so in the entrypoint script. This seems to fail due to ownership/permissions issues in some environments (at least in K8s with cass-operator).

We should put the file removal in the Dockerfiles themselves instead of the entrypoint script.

### PR DESCRIPTION
**Pull request by emerkle826**
Fixes #477

### CODE REVIEW

**Comment by emerkle826** [comment]
@burmanm I have tested images created with this PR in the cass-operator tests and Management API starts up correctly.

File: management-api-server/src/test/java/com/datastax/mgmtapi/BaseDockerIntegrationTest.java [hunk 1]
```diff
@@ -167,6 +167,15 @@ protected ArrayList<String> getEnvironmentVars() {
         "DSE_MGMT_EXPLICIT_START=true");
   }
 
+  protected String getUser() {
+    // The default should be either "cassandra:root" or "dse:root"
+    // Subclasses can override this to test alternate user behavior
+    if (this.version.startsWith("dse")) {
```
Comment (burmanm) [inline management-api-server/src/test/java/com/datastax/mgmtapi/BaseDockerIntegrationTest.java:173]: "dse:root" ?

The DSE test fails now.

Comment (emerkle826) [reply management-api-server/src/test/java/com/datastax/mgmtapi/BaseDockerIntegrationTest.java:173]: The DSE tests are passing in this PR now. I also loaded the image into my Kind cluster for cass-operator and ran the tests against that and it is working for me.

**Review by burmanm — APPROVED** [review]
